# Tool registry
from app.tools.file_ops import TOOLS as FILE_TOOLS, TOOL_SCHEMAS as FILE_SCHEMAS
from app.tools.transforms import TOOLS as TRANSFORM_TOOLS, TOOL_SCHEMAS as TRANSFORM_SCHEMAS
from app.tools.cleaning import TOOLS as CLEANING_TOOLS, TOOL_SCHEMAS as CLEANING_SCHEMAS
from app.tools.analytics import TOOLS as ANALYTICS_TOOLS, TOOL_SCHEMAS as ANALYTICS_SCHEMAS

TOOLS = {
    **FILE_TOOLS,
    **TRANSFORM_TOOLS,
    **CLEANING_TOOLS,
    **ANALYTICS_TOOLS,
}

TOOL_SCHEMAS = FILE_SCHEMAS + TRANSFORM_SCHEMAS + CLEANING_SCHEMAS + ANALYTICS_SCHEMAS

